import Link from 'next/link';
import { ArrowRight } from 'lucide-react';
import { title, number, artwork } from '@/lib/pokeapi';
import { PokemonImage } from '@/components/pokemon-image';
import { TypeBadge } from '@/components/type-badge';
import { parseSearch, searchPokemon, GENERATIONS, SearchInputError } from '@/lib/search';
import { SearchInput } from '@/components/search-input';
import { TYPES } from '@/lib/types';
export const dynamic = 'force-dynamic';
export default async function Home({searchParams}: {searchParams: Promise<Record<string,string|string[]|undefined>>}) {
  const params=new URLSearchParams();
  Object.entries(await searchParams).forEach(([key,value])=>{if(typeof value==='string')params.set(key,value);});
  let options;
  try { options=parseSearch(params); } catch(error) { if(error instanceof SearchInputError)return <div className="page"><div className="empty"><h1>Check those filters.</h1><p>{error.message}</p><Link className="button" href="/">Reset filters</Link></div></div>; throw error; }
  const {results:pokemon,total,nationalTotal,page,pages}=await searchPokemon(options);
  const pageUrl=(n:number)=>{const p=new URLSearchParams(params);p.set('page',String(n));return `/?${p.toString()}`;};
  return <div className="page"><section className="intro"><div><div className="eyebrow"><span className="status-dot"/> THE NATIONAL POKÉDEX</div><h1>A world worth<br/><em>discovering.</em></h1><p>Get to know every Pokémon. Find your favorites.<br/>Discover what makes them extraordinary.</p></div><Link href="/matchup" className="lab-teaser"><span className="eyebrow">THE TYPE LAB</span><h2>Know your<br/>next matchup.</h2><span>Explore type advantages <ArrowRight size={18}/></span></Link></section><form className="filters" action="/" role="search"><SearchInput initial={options.q}/><label><span className="sr-only">Type</span><select name="type" defaultValue={options.type}><option value="">All types</option>{TYPES.map(t=><option key={t} value={t}>{title(t)}</option>)}</select></label><label><span className="sr-only">Generation</span><select name="generation" defaultValue={options.generation||''}><option value="">All generations</option>{GENERATIONS.map((g,i)=><option key={g} value={i+1}>{i+1} · {g}</option>)}</select></label><label><span className="sr-only">Sort order</span><select name="sort" defaultValue={options.sort}><option value="number">Number ↑</option><option value="number-desc">Number ↓</option><option value="name">Name A–Z</option></select></label><button className="button primary" type="submit">Explore</button></form><div className="section-heading"><h2>Explore Pokémon <span>{total.toLocaleString()}</span></h2><span>{total === nationalTotal ? "The complete National Pokédex" : `${total} of ${nationalTotal} Pokémon`} · Page {page} of {pages}</span></div><div className="pokemon-grid">{pokemon.map(p => <Link href={`/pokemon/${p.dexName}`} className={`pokemon-card card-${p.types[0].type.name}`} key={p.id}><span className="dex-number">{number(p.id)}</span><PokemonImage src={artwork(p)} alt={title(p.name)}/><div className="card-bottom"><h3>{title(p.name)}</h3><ArrowRight size={18}/></div><div className="types">{p.types.map(t => <TypeBadge key={t.type.name} type={t.type.name}/>)}</div></Link>)}</div>{!pokemon.length&&<div className="empty"><h2>No Pokémon in sight.</h2><p>Try another name, number, or combination of filters.</p><Link href="/" className="button">Clear filters</Link></div>}<div className="pagination">{page>1?<Link className="button" href={pageUrl(page-1)}>← Previous</Link>:<span/>}<span>Page {page} of {pages}</span>{page<pages?<Link className="button" href={pageUrl(page+1)}>Next page →</Link>:<span/>}</div></div>;
}
